-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 18:26:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mealplan2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mealplan2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mealplan2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema mealplan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mealplan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mealplan` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mealplan2` ;

-- -----------------------------------------------------
-- Table `mealplan2`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mealplan2`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mealplan2`.`dinner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mealplan2`.`dinner` (
  `dinnerid` INT NOT NULL AUTO_INCREMENT,
  `monday` VARCHAR(45) NOT NULL,
  `tuesday` VARCHAR(45) NOT NULL,
  `wednesday` VARCHAR(45) NOT NULL,
  `thursday` VARCHAR(45) NOT NULL,
  `friday` VARCHAR(45) NOT NULL,
  `saturday` VARCHAR(45) NOT NULL,
  `sunday` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dinnerid`),
  CONSTRAINT `idusers`
    FOREIGN KEY (`dinnerid`)
    REFERENCES `mealplan2`.`users` (`idusers`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `mealplan` ;

-- -----------------------------------------------------
-- Table `mealplan`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mealplan`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mealplan`.`dinner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mealplan`.`dinner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sunday` VARCHAR(100) NOT NULL,
  `monday` VARCHAR(100) NOT NULL,
  `tuesday` VARCHAR(100) NOT NULL,
  `wednesday` VARCHAR(100) NOT NULL,
  `thursday` VARCHAR(100) NOT NULL,
  `friday` VARCHAR(100) NOT NULL,
  `saturday` VARCHAR(100) NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dinner_users_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_dinner_users`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mealplan`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
